// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwmpyprirzjmxrveiole.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bXB5cHJpcnpqbXhydmVpb2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzIyOTAsImV4cCI6MjA1NTY0ODI5MH0.ZMQ7SpdCyt2qlzkI5UBAS8ci8MwSaOVrTngglrP1xRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);